# Generated by Django 5.1.1 on 2024-10-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0003_merge_20241024_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
