# Generated by Django 5.1.1 on 2024-10-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetail', '0001_initial'),
        ('product', '0003_merge_20241024_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='productId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
