# Generated by Django 5.1.1 on 2024-10-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('orderDetail', '0002_alter_orderdetail_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order'),
        ),
    ]
