# Generated by Django 5.1.1 on 2024-10-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('mainCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('SubCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('SubCategoryName', models.CharField(max_length=100)),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.maincategories')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategories')),
            ],
        ),
    ]
