# Generated by Django 5.1.1 on 2024-10-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_image'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
