# Generated by Django 5.1.1 on 2024-10-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeId', models.AutoField(primary_key=True, serialize=False)),
                ('sizeName', models.CharField(max_length=20)),
                ('sizeValue', models.FloatField()),
            ],
        ),
    ]
