# Generated by Django 5.1.1 on 2024-11-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('size_numeric', models.IntegerField(blank=True, null=True)),
                ('size_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
