# Generated by Django 5.1.1 on 2024-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sizeName',
        ),
        migrations.RemoveField(
            model_name='size',
            name='sizeValue',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size_numeric',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
