# Generated by Django 5.1.1 on 2024-10-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodcut_id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('subHeading', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categories')),
            ],
        ),
    ]
