# Generated by Django 5.1.1 on 2024-10-23 15:58

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]
    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_id',
            new_name='productId',
        ),
    ]