# Generated by Django 5.1.1 on 2024-10-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
        ('product', '0002_rename_prodcut_id_product_productid'),
    ]

    operations = [
    ]
