# Generated by Django 5.1.1 on 2024-10-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
        ('product', '0001_initial'),
        ('sizes', '0002_remove_size_sizename_remove_size_sizevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOnProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizes.size')),
            ],
            options={
                'verbose_name': 'Color on Product',
                'verbose_name_plural': 'Colors on Products',
                'db_table': 'color_on_product',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
