# Generated by Django 5.1.1 on 2024-10-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorOnProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloronproduct',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='coloronproduct',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='coloronproduct',
            table=None,
        ),
    ]
