# Generated by Django 5.1.1 on 2024-10-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorOnProduct', '0002_alter_coloronproduct_options_and_more'),
        ('colors', '0001_initial'),
        ('product', '0003_merge_20241024_0924'),
        ('sizes', '0002_remove_size_sizename_remove_size_sizevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloronproduct',
            options={'verbose_name': 'Color on Product', 'verbose_name_plural': 'Colors on Products'},
        ),
        migrations.AlterUniqueTogether(
            name='coloronproduct',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.AlterModelTable(
            name='coloronproduct',
            table='color_on_product',
        ),
    ]
